"""empty message

Revision ID: 94e459e0bb24
Revises: 
Create Date: 2021-01-03 19:59:43.325622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e459e0bb24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('product', sa.Column('primary_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'product_image', ['primary_image_id'], ['id'])
    op.create_foreign_key(None, 'product_type', 'product_type', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_type', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'primary_image_id')
    op.drop_table('product_image')
    # ### end Alembic commands ###
